name: Build EXE for Windows

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        pip install pyinstaller
        pip install -r requirements.txt || echo "No requirements.txt found"

    - name: Build EXE
      run: |
        pyinstaller --onefile --noconsole BaiKHKT.py

    - name: Upload EXE artifact
      uses: actions/upload-artifact@v4
      with:
        name: BaiKHKT-Windows
        path: dist/BaiKHKT.exe
