name: Build baikhkt.exe for Windows

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install pyinstaller
          pip install requests beautifulsoup4 python-docx fpdf reportlab sentence-transformers torch

      - name: Build EXE
        run: |
          pyinstaller --onefile --noconsole baikhkt.py

      - name: Create ZIP package
        run: |
          cd dist
          powershell Compress-Archive -Path baikhkt.exe -DestinationPath baikhkt-Windows.zip

      - name: Upload EXE artifact
        uses: actions/upload-artifact@v4
        with:
          name: baikhkt-Windows
          path: dist/baikhkt-Windows.zip


